name: SmokeOnTeleport
version: '${project.version}'
main: com.akyrossoftware.plugins.smokeonteleport.SmokeOnTeleport
api-version: 1.18
commands:
    
  smoketp:
    description: used to reload or change config of smoke on teleport
    usage: /<command>
